name: Generate Snake Animation

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Generate Snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: srijan1110
          outputs: dist/snake.svg

      # Step 3: Push the generated SVG
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: Update Snake Animation"
          add: "dist/snake.svg"
