name: Generate World Map

on:
  schedule:
    # Run once a day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the World Map
      - name: Generate Map
        run: |
          mkdir -p dist
          echo '<!DOCTYPE html>
          <html>
          <head>
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
          </head>
          <body>
            <canvas id="myChart" width="400" height="400"></canvas>
            <script>
              const ctx = document.getElementById("myChart").getContext("2d");
              const data = {
                labels: ["North America", "Europe", "Asia", "Other"],
                datasets: [{
                  label: "Visitors",
                  data: [40, 30, 20, 10],
                  backgroundColor: ["#FF6384", "#36A2EB", "#FFCE56", "#4BC0C0"],
                  hoverOffset: 4
                }]
              };
              const config = {
                type: "doughnut",
                data: data,
              };
              new Chart(ctx, config);
            </script>
          </body>
          </html>' > dist/map.html

      # Step 3: Commit the Map
      - name: Commit and Push Map
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update World Map"
          add: "dist/map.html"
