name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  generate-pacman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or '18'

      - name: Install dependencies
        run: npm install

      - name: Generate Pac-Man SVG
        run: npm run generate  # This runs "node index.js" as per the package.json

      - name: Upload Pac-Man SVG to pac branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: pac
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
