name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Generate Snake SVG
        run: |
          mkdir -p dist
          curl -o dist/github-snake.svg "https://github.com/Platane/snk/raw/output/github-contribution-grid-snake.svg"

      - name: Upload the Snake SVG
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: snake-game
          path: dist/github-snake.svg
